### ISSUE TITLE
Altitude Hold with Laser Rangefinder Feedback Loop

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/Flight-Controller#13]
I tested the most recent firmware release today, and while the barometric pressure and PING))) altitude hold modes perform well, using the SF11/C Laser Rangefinder causes an oscillatory feedback "loop", whereby as soon as the laser-assisted altitude hold is enable, the ELEV-8 begins to oscillate vertically (moves down vertically, then back up, then back down), and the magnitude of the oscillations (distance up/dwn) quickly increases with time.

I had wireless telemetry set up during the tests. Here is the graph of distance to ground over time, showing the oscillations
![osc1](https://cloud.githubusercontent.com/assets/13735732/17497340/41a30cc6-5d76-11e6-96ec-c8f2e99a0799.png)

I then tried changing the Altitude PID from 125 to 70, thinking that maybe the value was just to aggressive, but it didn't have any noticeable effect:
![laser2](https://cloud.githubusercontent.com/assets/13735732/17497494/fa53d926-5d76-11e6-8b2f-765537e61646.png)

If I had to guess, I would think that a sign is reversed somewhere.

**Comment by MatzElectronics** [comment]
This appears to be solved by removing the filtering on the SF-11C, which is turned on by default.  @RoboTechie has drafted instructions
