### ISSUE TITLE
Improve telemetry communications

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/Flight-Controller#23]
Implement xon-xoff in FTDI chip, GS, and FC.  This is a breaking change.

**Comment by JasonDorie** [comment]
XOn / Off is software only, so the FTDI shouldn't need to be involved.  Not
sure what the benefit would be though.  At some point, packets will get
lost.  I'd rather they were the old packets, not the new ones.  Reduce the
XBee retry counts, and possibly switch to using API mode with the XBee
instead of pass-through (if it can be done without requiring additional
pins).

J

**Comment by MatzElectronics** [comment]
Open to suggestions, or even calling where it's at good enough...

**Comment by JasonDorie** [comment]
I just want to know what you expect to get from enabling flow control.  It
would mean not corrupting packets on slow delivery, but the packet loss
itself is from the XBee failing transmission.  If loss happens, flow
control will make new data wait for old data to finish going through, but
for realtime display, it's more relevant to have new data prioritized over
old data.  It's never going to be a lossless connection.

I was thinking it would be worthwhile breaking the comms and making new
packet types that were packed.  I'm using 16 bits to transmit each radio
value, even though they're only 11 bits each.  Ditto for motor values, and
others could be reduced similarly.  It would cost a bit of code time to
pack them, but there'd be less to send, so more room for retries.

J

**Comment by JasonDorie** [comment]
Telemetry comm is now using less data per packet, and packet transmit rate has been reduced by 20% (coinciding with 20% reduction in update rate), giving more time for retries.  In theory, this should improve reliability - can one of you check this?

**Comment by MatzElectronics** [comment]
I might be able to tomorrow, I'll let you know either way

**Comment by MatzElectronics** [comment]
Closing - addressed in #40.
