### ISSUE TITLE
Improve radio calibration

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/Flight-Controller#35]
mis-calibration detection and/or just simpler (move sticks around, individually push switches forward)

**Comment by MatzElectronics** [comment]
Tested and verified.  Docs will require updating.

**Comment by JasonDorie** [comment]
Be sure to note in the docs that you can update any combination of sticks /
knobs / switches.  Any that you don't move will retain their previous
settings, meaning that if you mess one up you don't have to redo all of
them.
