### ISSUE TITLE
Add all/none to checkboxes in GS sensors tab

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/Flight-Controller#39]

**Comment by JasonDorie** [comment]
Done (not submitted yet, but tested).

I've also added a "Clear Data" button, and made the graph not wrap or purge
old data in prep for writing it out to disk.  Presumably you won't want the
6000 sample limit for that, which is what it was previously set to.

I've created a new branch called ActiveDevelopment which I'll use going
forward.  When a version is stable and tested, I'll merge back to main and
release from there.

J

**Comment by MatzElectronics** [comment]
Perfect! Thanks!
