### ISSUE TITLE
Mac Ground Station Versioning and Telemetry

### ISSUE THREAD

**Issue by jrleeman** [parallaxinc/Flight-Controller#41]
In the 2.0 release the ground station is still labeled "1.1.1" in the footer of the program and will not connect to a telemetry system that works well on the Windows version of the ground station.

**Comment by MatzElectronics** [comment]
@jrleeman have you tried reinstalling the FTDI driver for the mac?  I think the next rebuild of 2.0.0 corrects the version on the bottom - @JasonDorie can you verifiy that?

**Comment by jrleeman** [comment]
New FTDI VCP solved this. Not sure why it was necessary. Now just to get that version number.

**Comment by MatzElectronics** [comment]
Yes, that's coming - thanks!  I'll close this issue.

_Matthew Matz  |  STEM/Robotics Educator_
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics http://twitter.com/MatzElectronics
