### ISSUE TITLE
Laser Rangefinder Altitude Hold Tuning

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/Flight-Controller#45]
While disabling the median filter on the SF11-C ([Instructions here](https://github.com/parallaxinc/Flight-Controller/wiki/Flight-Controller-Wiki-Homepage)) fixes the catastrophic oscillations described in [Issue 13](https://github.com/parallaxinc/Flight-Controller/issues/13), the ELEV-8 still oscillates 10-50 cm vertically without ever settling out when using the SF11-C for altitude hold, so any improvements to reduce this would be well received.

**Comment by MatzElectronics** [comment]
Closing, copying text from above into #21.
