### ISSUE TITLE
Set "Audible Low Voltage Alarm" to disabled by default

### ISSUE THREAD

**Issue by RoboTechie** [parallaxinc/Flight-Controller#46]
The hardware is simply too inaccurate (at least until the offset is adjusted) for this to be on by default. I tested out v2.0.0 on a Rev B1 board and the low voltage buzzer went off the first time I ever plugged in a battery (which was fully charged) - customers shouldn't have to experience that.

The voltage circuit is very useful for some of the safety features, but as is currently implemented in hardware/software, just too erratic to have customers rely heavily on until they understand its limitations.

**Comment by MatzElectronics** [comment]
Committed to master
