### ISSUE TITLE
Validate gyro calibration

### ISSUE THREAD

**Issue by JasonDorie** [parallaxinc/Flight-Controller#51]
Add code to characterize the quality of gyro calibration.

- Range of temperature measurement should be broad enough for good line fit
- Range of gyro readings within measurement range should be within some max dist of chosen line
- detect bumps & auto reset?
- Display small indicator like "pending" (red) and change to "complete" (green)

**Comment by JasonDorie** [comment]
Partly done - now in FloatStreamCompiler branch.  Doesn't auto reset, but quantifies noise and range.

**Comment by MatzElectronics** [comment]
Tested and verified.  The only concern I have is that when I clicked "upload calibration" both bars went red.  I understand why, but docs need to explain what's happening there.

**Comment by JasonDorie** [comment]
I could make it put a message in there in green saying "upload successful"
or something for 5 seconds after you upload.  Less confusing.

**Comment by MatzElectronics** [comment]
Sounds good, if you can, make it so!

_Matthew Matz  |  STEM/Robotics Educator_
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics http://twitter.com/MatzElectronics
